version: '3'

services:

  mongodb:
    image: mongo:3.6
    container_name: mongodb-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  estat-express:
    image: estat/estatcamp-express
    container_name: estat-express-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=estatcamp
      - ME_CONFIG_BASICAUTH_PASSWORD=estatcamp
      - ME_CONFIG_OPTIONS_NO_DELETE=true
      - ME_CONFIG_OPTIONS_READONLY=true
      - ME_CONFIG_OPTIONS_NO_IMPORT=true
    depends_on:
      - mongodb

  api:
    build: .
    container_name: api
    command: npm start
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb-api:27017/
    ports:
      - "4000:4000"
    depends_on:
      - estat-express

  login:
    image: estat/login
    container_name: login-api
    restart: on-failure
    command: npm start
    ports:
      - "80:8080"
    depends_on:
      - api
