version: '3'

services:

  mongodb:
    image: mongo:3.6
    container_name: mongodb-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  estat-express:
    image: estat/estatcamp-express
    container_name: estat-express-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=estatcamp
      - ME_CONFIG_BASICAUTH_PASSWORD=estatcamp
      - ME_CONFIG_OPTIONS_NO_DELETE=true
      - ME_CONFIG_OPTIONS_READONLY=true
      - ME_CONFIG_OPTIONS_NO_IMPORT=true
    depends_on:
      - mongodb

  api:
    build: .
    container_name: api
    command: npm start
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb-api:27017/
      - NODE_ENV=production
    depends_on:
      - estat-express
    labels:
      - "traefik.http.routers.api.rule=Host(`api.docker.localhost`)"

  login:
    image: estat/login
    container_name: login
    restart: on-failure
    command: ./entrypoint.sh
    environment:
      - VUE_APP_REDIRECT_URL=https://google.com
      - API_URL=http://api.docker.localhost
    depends_on:
      - api
    labels:
      - "traefik.http.routers.login.rule=Host(`login.docker.localhost`)"
      - "traefik.http.middlewares.login.headers.customrequestheaders.Access-Control-Allow-Origin=*.docker.localhost"

  reverse-proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
